### ISSUE TITLE
docker build无法下载问题

### ISSUE THREAD

**Issue by limmi001** [jmwang0117/AGRNav#2]
![7BF53573ECD775646BC4C02F2B108DE3](https://github.com/user-attachments/assets/bb542492-787b-43f0-b5c4-bf001270852d)
作者您好！我在docker build时遇到了一些问题，执行后总是卡在这里，一些内容无法下载，希望您受累看一下，感谢！

**Comment by jmwang0117** [comment]
> ![7BF53573ECD775646BC4C02F2B108DE3](https://private-user-images.githubusercontent.com/84947319/363478769-bb542492-787b-43f0-b5c4-bf001270852d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTAxNTUsIm5iZiI6MTcyNTE4OTg1NSwicGF0aCI6Ii84NDk0NzMxOS8zNjM0Nzg3NjktYmI1NDI0OTItNzg3Yi00M2YwLWI1YzQtYmYwMDEyNzA4NTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDExMjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YTFhZWM4ZDViYjg1YjUwMTY3ZjhkMTU0MjY3YjMzMDVkNjJhMjQ2YTUwYWExOGE5YzA5NDk3M2U4MmUyOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YPCZGPQqGPijFD8yHvVmxFJYfB0m5CFYA94-OFgWmo8) 作者您好！我在docker build时遇到了一些问题，执行后总是卡在这里，一些内容无法下载，希望您受累看一下，感谢！

你可以单独拉取这个cudagl这个镜像吗？如果不能且你在中国大陆，你可能需要先安装VPN后在进行拉取！

**Comment by limmi001** [comment]
非拆感谢！确实是代理的问题，已经解决了：）

**Comment by qq0805** [comment]
你好~请问你复现成功了吗 我遇到有些bug不会处理 可否留个联系方式交流一下？
